import { AUTH0_CLIENT_ID, AUTH0_DOMAIN, AUTHO_SCOPE, AZURE_ACCOUNT_NAME } from 'react-native-dotenv';
export default {
  AZURE_ACCOUNT_NAME: AZURE_ACCOUNT_NAME,
  AUTH0_CLIENT_ID: AUTH0_CLIENT_ID,
  AUTH0_DOMAIN: AUTH0_DOMAIN,
  AUTHO_SCOPE: AUTHO_SCOPE,
};